---
title: Sample post - Interactive tables and graphs in R
author: Danny Morris
summary: This post demonstrates the use of DT, ggplot2, and plotly R packages for rendering beautiful tables and graphs in an R Markdown document.
date: '2021-04-22'
output:
  blogdown::html_page:
    highlight: tango
    toc: true
slug: []
categories:
  - R
  - R Markdown
  - DT
  - Plotly
  - Covid19
tags:
  - R
  - R Markdown
  - DT
  - Plotly
  - Covid19
Description: 'Add additional information about the post using keywords to improve SEO'
Tags: []
Categories: []
DisableComments: no
editor_options: 
  chunk_output_type: console
---

```{r, include=F}
knitr::opts_chunk$set(message = F, warning = F, echo = T)
```

# Overview

This post written with R Markdown demonstrates the use of DT, ggplot2, and plotly R packages for rendering beautiful tables and graphs.

# R packages

```{r}
library(readr)
library(dplyr)
library(tidyr)
library(ggplot2)
library(DT)
library(plotly)
```

# Data

```{r}
covid_ny <- read_csv("https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-states.csv") %>%
  filter(state == "New York")

covid_ny
```

# Tables using DT

```{r}
DT::datatable(covid_ny)
```

# Visualizations using ggplot2 

```{r}
covid_ny %>%
  gather(key, value, cases, deaths) %>%
  ggplot(aes(x = date, y = value)) +
  facet_wrap(~key, scales = "free_y") +
  geom_line(color = "#02718f") +
  labs(title = "Cumulative Covid-19 cases and deaths in the state of New York, USA") +
  theme_bw()
```

# Visualizations using plotly

```{r}
covid_ny %>%
  plot_ly(x = ~date, y = ~cases) %>%
  add_markers() %>%
  layout(title = "Cumulative Covid-19 cases and deaths in the state of New York, USA")
```
